version: "3.3"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./deployment/mysql/master/conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./deployment/mysql/master/conf/my.cnf:/etc/mysql/my.cnf
    networks:
      - backend
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    restart: unless-stopped
    depends_on:
      - rabbitmq
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      SESSION_SECRET_KEY: ${SESSION_SECRET_KEY}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_COOKIE: ${RABBITMQ_COOKIE}
      RABBITMQ_FEED_EXCHANGE_NAME: ${RABBITMQ_FEED_EXCHANGE_NAME}
      RABBITMQ_FEED_QUEUE_NAME: ${RABBITMQ_FEED_QUEUE_NAME}
      RABBITMQ_FEED_ROUTING_KEY: ${RABBITMQ_FEED_ROUTING_KEY}
      RABBITMQ_FEED_RECEIVERS_COUNT: ${RABBITMQ_FEED_RECEIVERS_COUNT}
    networks:
      - backend
networks:
  backend:
