version: "3.3"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "hsn"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "niklod"
      # You can use whatever password you like
      MYSQL_PASSWORD: "testpassword"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "testpassword"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - mysql:/var/lib/mysql
# Names our volume
volumes:
  mysql:
